// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR-FwzCC7A7wPlf84-U4iRIkxS23wCbbQ',
    appId: '1:1011322842086:web:453d7dd27dd17cc23a4427',
    messagingSenderId: '1011322842086',
    projectId: 'chat-app-ai-3723b',
    authDomain: 'chat-app-ai-3723b.firebaseapp.com',
    storageBucket: 'chat-app-ai-3723b.firebasestorage.app',
    measurementId: 'G-CMB6SFT7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLnKwnucwAB9GgYpn6K5GsYeBKOm_iIo',
    appId: '1:1011322842086:android:ac58e46abfe582ae3a4427',
    messagingSenderId: '1011322842086',
    projectId: 'chat-app-ai-3723b',
    storageBucket: 'chat-app-ai-3723b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCp7HUJklkgSYLLSYBEPImu8zXru6ocrI',
    appId: '1:1011322842086:ios:649a76c6d637c8a73a4427',
    messagingSenderId: '1011322842086',
    projectId: 'chat-app-ai-3723b',
    storageBucket: 'chat-app-ai-3723b.firebasestorage.app',
    iosBundleId: 'com.example.chatAppAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCp7HUJklkgSYLLSYBEPImu8zXru6ocrI',
    appId: '1:1011322842086:ios:649a76c6d637c8a73a4427',
    messagingSenderId: '1011322842086',
    projectId: 'chat-app-ai-3723b',
    storageBucket: 'chat-app-ai-3723b.firebasestorage.app',
    iosBundleId: 'com.example.chatAppAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR-FwzCC7A7wPlf84-U4iRIkxS23wCbbQ',
    appId: '1:1011322842086:web:107a09b137ba4ca93a4427',
    messagingSenderId: '1011322842086',
    projectId: 'chat-app-ai-3723b',
    authDomain: 'chat-app-ai-3723b.firebaseapp.com',
    storageBucket: 'chat-app-ai-3723b.firebasestorage.app',
    measurementId: 'G-0TPMBMXS4V',
  );
}
